services:
  backend:
    image: rp35/seplag-servidores
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - seplag-network
    depends_on:
      - database
      - minio

  database:
    image: postgres:17
    container_name: postgres
    environment:
      POSTGRES_USER: seplag
      POSTGRES_PASSWORD: e8iQi1OacIFRtiyyL03GPEDaS13j3j5b
      POSTGRES_DB: seplag-servidores
    ports:
      - "5432:5432"
    networks:
      - seplag-network

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: seplag
      MINIO_ROOT_PASSWORD: e8iQi1OacIFRtiyyL03GPEDaS13j3j5b
    command: server /data --console-address ":9001"
    networks:
      - seplag-network
    volumes:
      - minio_data:/data

networks:
  seplag-network:
    driver: bridge

volumes:
  minio_data: